services:
  - type: web
    name: job-scraper-api
    env: python
    region: oregon
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PIP_DEFAULT_TIMEOUT
        value: 100
